language: node_js
node_js:
  - "10"
dist: trusty
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  # - ng lint
  # - npm run test-headless
  - ng build --prod --base-href https://vanarenan.github.io/angular-lab/
deploy:
  provider: pages
  token: $GITHUB_TOKEN
  local_dir: dist/angular-lab
  on:
    branch: master
